import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0c0c14',
  },

  // ─── Top bar ───────────────────────────────────────────────────────────────
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 8,
    backgroundColor: '#0c0c14',
    zIndex: 10,
  },
  backBtn: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBarCenter: {
    alignItems: 'center',
  },
  frozenBtn: {
    backgroundColor: 'rgba(239,68,68,0.15)',
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
  },
  frozenBtnText: {
    color: '#EF4444',
    fontSize: 13,
    fontWeight: '800',
  },
  minutesRight: {
    alignItems: 'flex-end',
    minWidth: 80,
  },
  minutesText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
    fontStyle: 'italic',
  },
  timerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  greenDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#22C55E',
  },
  timerText: {
    color: '#22C55E',
    fontSize: 14,
    fontWeight: '800',
  },
  searchingText: {
    color: '#A1A1AA',
    fontSize: 12,
    fontWeight: '600',
  },

  // ─── Main area ────────────────────────────────────────────────────────────
  mainArea: {
    flex: 1,
    position: 'relative',
  },

  // ─── Idle ─────────────────────────────────────────────────────────────────
  idleArea: {
    flex: 1,
    position: 'relative',
  },
  idlePreview: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 130,
    height: 175,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#1E1E38',
    borderWidth: 1.5,
    borderColor: '#2A2A4A',
    zIndex: 10,
  },
  idlePreviewRTC: {
    width: '100%',
    height: '100%',
  },
  idlePreviewPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  voiceToggle: {
    position: 'absolute',
    bottom: 20,
    alignSelf: 'center',
    left: 0,
    right: 0,
    marginHorizontal: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#1E1E38',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#2A2A4A',
  },
  voiceToggleText: {
    color: '#A1A1AA',
    fontSize: 13,
    fontWeight: '600',
  },
  voiceAvatarCircle: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  voiceModeLabel: {
    color: '#A1A1AA',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 10,
  },

  // ─── Waiting ──────────────────────────────────────────────────────────────
  waitingArea: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1A1A2E',
  },
  waitingPulseSection: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 200,
    height: 200,
    marginBottom: 32,
  },
  pulseRing: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(239,68,68,0.12)',
  },
  pulseRingInner: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(239,68,68,0.2)',
  },
  waitingContent: {
    alignItems: 'center',
    zIndex: 10,
    marginBottom: 24,
  },
  waitingTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
  },
  waitingTimer: {
    color: '#A1A1AA',
    fontSize: 18,
    fontWeight: '700',
    marginTop: 10,
  },
  waitingSubText: {
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 19,
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  waitingMessageSection: {
    alignItems: 'center',
    marginTop: 16,
  },
  waitingDiscoverBtn: {
    backgroundColor: 'rgba(239,68,68,0.12)',
    borderRadius: 20,
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
  },
  waitingDiscoverBtnText: {
    color: '#EF4444',
    fontSize: 14,
    fontWeight: '700',
  },

  // ─── Video area ───────────────────────────────────────────────────────────
  videoArea: {
    flex: 1,
    position: 'relative',
    backgroundColor: '#000',
  },
  remoteVideo: {
    flex: 1,
  },
  remoteVideoPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0c0c14',
  },
  topicsRow: {
    position: 'absolute',
    top: 12,
    left: 0,
    right: 0,
  },
  topicsContent: {
    paddingHorizontal: 12,
    gap: 6,
  },
  topicChip: {
    backgroundColor: 'rgba(0,0,0,0.55)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    marginRight: 6,
  },
  topicChipText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  reportBtn: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: 'rgba(0,0,0,0.55)',
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  localPip: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    width: 120,
    height: 160,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#1E1E38',
    borderWidth: 2,
    borderColor: '#333',
    alignItems: 'center',
    justifyContent: 'center',
  },
  localPipRTC: {
    width: '100%',
    height: '100%',
  },
  pipPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1A1A2E',
  },
  partnerChipsContainer: {
    position: 'absolute',
    top: 56,
    right: 12,
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: 6,
    maxWidth: 160,
  },
  partnerChip: {
    backgroundColor: '#1D4ED8',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#3B82F6',
  },
  partnerChipText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  myChipsContainer: {
    position: 'absolute',
    bottom: 180,
    left: 12,
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 6,
    maxWidth: 160,
  },
  myChip: {
    backgroundColor: '#EF4444',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#DC2626',
  },
  myChipText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  topicsTab: {
    position: 'absolute',
    left: -28,
    top: '28%',
    backgroundColor: 'rgba(0,0,0,0.75)',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    zIndex: 10,
    transform: [{ rotate: '-90deg' }],
  },
  topicsTabText: {
    fontSize: 12,
  },
  topicsTabLabel: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  topicsTabBadge: {
    backgroundColor: '#FFFFFF',
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  topicsTabBadgeText: {
    color: '#EF4444',
    fontSize: 10,
    fontWeight: '900',
  },

  // ─── Gender filter ────────────────────────────────────────────────────────
  genderFilterRow: {
    flexDirection: 'row',
    backgroundColor: '#2A2A4A',
    borderRadius: 50,
    padding: 5,
    marginBottom: 12,
    marginHorizontal: 16,
  },
  genderPill: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 3,
  },
  genderPillActive: {
    backgroundColor: '#EF4444',
  },
  genderPillText: {
    color: '#A1A1AA',
    fontSize: 14,
    fontWeight: '700',
  },
  genderPillTextActive: {
    color: '#FFFFFF',
    fontWeight: '900',
  },

  // ─── Bottom bar ───────────────────────────────────────────────────────────
  bottomBar: {
    backgroundColor: '#0c0c14',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: '#2A2A4A',
  },
  selfieBtn: {
    backgroundColor: '#EC4899',
    borderRadius: 50,
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selfieBtnText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  startBtn: {
    backgroundColor: '#EF4444',
    borderRadius: 50,
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  startBtnText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  cancelBtn: {
    borderRadius: 50,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#EF4444',
  },
  cancelBtnText: {
    color: '#EF4444',
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 1,
  },
  callControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  ctrlBtn: {
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  ctrlLabel: {
    color: '#A1A1AA',
    fontSize: 10,
    fontWeight: '600',
  },
  nextBtn: {
    backgroundColor: '#EF4444',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 50,
  },
  nextBtnText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '900',
  },
  endCallBtn: {
    backgroundColor: '#EF4444',
    borderRadius: 50,
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ─── Toast ────────────────────────────────────────────────────────────────
  minuteLossToast: {
    position: 'absolute',
    top: 60,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(20,20,30,0.9)',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 18,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#EF4444',
    zIndex: 100,
  },
  minuteLossToastText: {
    color: '#EF4444',
    fontSize: 14,
    fontWeight: '800',
  },

  // ─── Modals ───────────────────────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  modalCard: {
    backgroundColor: '#1E1E38',
    borderRadius: 24,
    padding: 28,
    width: '100%',
    maxWidth: 360,
    borderWidth: 1,
    borderColor: '#2A2A4A',
    gap: 12,
  },
  modalTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
  },
  modalSubtitle: {
    color: '#A1A1AA',
    fontSize: 14,
    textAlign: 'center',
  },
  modalRedBtn: {
    backgroundColor: '#EF4444',
    borderRadius: 50,
    paddingVertical: 16,
    alignItems: 'center',
  },
  modalRedBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  modalGrayBtn: {
    borderRadius: 50,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#2A2A4A',
  },
  modalGrayBtnText: {
    color: '#A1A1AA',
    fontSize: 15,
    fontWeight: '700',
  },
  disabledBtn: {
    opacity: 0.5,
  },
  remindLaterText: {
    color: '#A1A1AA',
    fontSize: 14,
    fontWeight: '600',
  },

  // ─── Report sheet ─────────────────────────────────────────────────────────
  reportModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  reportSheet: {
    backgroundColor: '#1E1E38',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
    borderTopWidth: 1,
    borderColor: '#2A2A4A',
  },
  reportHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  reportTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
  },
  reportGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  reportReasonBtn: {
    backgroundColor: '#2A2A4A',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#3A3A5A',
    width: '47%',
  },
  reportReasonBtnActive: {
    borderColor: '#EF4444',
    backgroundColor: 'rgba(239,68,68,0.12)',
  },
  reportReasonText: {
    color: '#A1A1AA',
    fontSize: 12,
    fontWeight: '600',
  },
  reportReasonTextActive: {
    color: '#EF4444',
  },
  reportDetailsInput: {
    backgroundColor: '#1A1A2E',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2A4A',
    color: '#FFFFFF',
    padding: 12,
    fontSize: 14,
    minHeight: 72,
    textAlignVertical: 'top',
  },
  reportSuccess: {
    paddingVertical: 24,
    alignItems: 'center',
  },
  reportSuccessText: {
    color: '#22C55E',
    fontSize: 16,
    fontWeight: '800',
  },

  // ─── Banned overlay ───────────────────────────────────────────────────────
  bannedOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#0c0c14',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 999,
  },
  bannedContent: {
    alignItems: 'center',
    paddingHorizontal: 40,
    gap: 12,
  },
  bannedIcon: {
    fontSize: 64,
  },
  bannedTitle: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '900',
  },
  bannedReason: {
    color: '#A1A1AA',
    fontSize: 15,
    textAlign: 'center',
  },
  bannedDate: {
    color: '#71717A',
    fontSize: 12,
  },

  // ─── Gift overlay ─────────────────────────────────────────────────────────
  giftModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  giftModalCard: {
    backgroundColor: '#111827',
    borderRadius: 24,
    padding: 24,
    width: '100%',
    maxWidth: 380,
    borderWidth: 1,
    borderColor: '#1F2937',
  },
  giftCloseBtn: {
    position: 'absolute',
    top: 14,
    right: 14,
    backgroundColor: '#EF4444',
    borderRadius: 18,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  giftModalTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 6,
    marginTop: 4,
    paddingRight: 36,
  },
  giftModalSubtitle: {
    color: '#9CA3AF',
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 6,
  },
  giftModalPaypal: {
    color: '#22C55E',
    fontSize: 13,
    textAlign: 'center',
    fontWeight: '600',
    marginBottom: 16,
  },
  giftTierWrapper: {
    marginBottom: 8,
  },
  giftTierBtn: {
    backgroundColor: '#10B981',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 52,
  },
  giftTierContent: {
    alignItems: 'center',
  },
  giftTierLabel: {
    color: '#000000',
    fontSize: 15,
    fontWeight: '900',
  },
  giftTierSublabel: {
    color: 'rgba(0,0,0,0.6)',
    fontSize: 11,
    fontWeight: '500',
    marginTop: 2,
  },
  giftTierBonus: {
    color: '#FACC15',
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 4,
  },
  giftNoRefund: {
    color: '#EF4444',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 12,
  },
});

export default styles;